import {React, useState} from 'react'
import { useAddBook } from '../hooks/addBook'
// id and isbn will be autogenerated

export default function Dashboard(){
  const [bookID, setBookID] = useState('')
  const [title, setTitle] = useState('')
  const [author, setAuthor] = useState('')
  const [isbn, setIsbn] = useState('')
  const [description, setDescription] = useState('')

  const handleAddBook = async () => {
    setBookID(crypto.randomUUID())
    setIsbn(Math.floor(1000000000000 + Math.random() * 9000000000000).toString())
    if(!title || !author || !isbn || !description) return
    await useAddBook(bookID, title, author, isbn, description)
    setBookID('')
    setTitle('')
    setAuthor('')
    setIsbn('')
    setDescription('')
  } 

  return (
    <div className='p-6'>
      <h2 className="text-xl font-semibold mb-4">Add books</h2>
      <div>
        <label className="block text-sm text-gray-600 mb-2">Title</label>
        <input value={title} onChange={e=>setTitle(e.target.value)} className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-gblue transition mb-4" placeholder="The Great Book" />
        <label className="block text-sm text-gray-600 mb-2">Author</label>
        <input value={author} onChange={e=>setAuthor(e.target.value)} className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-gblue transition mb-4" placeholder="John Doe" />
        <label className="block text-sm text-gray-600 mb-2">Description</label>
        <textarea value={description} onChange={e=>setDescription(e.target.value)} className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-gblue transition mb-4" placeholder="A fascinating book about..." rows={4} />
        <button className="px-6 py-3 rounded-lg bg-gblue text-white font-medium" onClick={handleAddBook}>Add Book</button>
      </div>
    </div>
  )
}